services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
        - action: rebuild
          path: ./frontend/next.config.ts
        - action: sync
          path: ./frontend
          target: /app
  backend:
    depends_on:
      - postgres
    build: ./backend
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/package-lock.json
        - action: sync
          path: ./backend
          target: /app
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: "False"

      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444

volumes:
  postgres_data:

configs:
  pgadmin-pgpass:
    content: |
      postgres:5432:*:postgres:secret
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Local Postgres",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/config/pgpass"
          }
        }
      }
